### ISSUE TITLE
:warning: Action Required: Replace Deprecated gcr.io/kubebuilder/kube-rbac-proxy

### ISSUE THREAD

**Issue by camilamacedo86** [openshift-kni/example-cnf#103]
## Description

:warning: **The image `gcr.io/kubebuilder/kube-rbac-proxy` is deprecated and will become unavailable.**
**You must move as soon as possible, sometime from early 2025, the GCR will go away.**

> _Unfortunately, we're unable to provide any guarantees regarding timelines or potential extensions at this time. Images provided under GRC will be unavailable from March 18, 2025, [as per announcement](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr). However, `gcr.io/kubebuilder/`may be unavailable before this date due [to efforts to deprecate infrastructure](https://github.com/kubernetes/k8s.io/issues/2647)._

- **If your project uses `gcr.io/kubebuilder/kube-rbac-proxy`, it will be affected.**
  Your project may fail to work if the image cannot be pulled. **You must take action as soon as possible.**

- However, if your project is **no longer using this image**, **no action is required**, and you can close this issue.

## Using the image `gcr.io/kubebuilder/kube-rbac-proxy`?

[kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) was historically used to protect the metrics endpoint. However, its usage has been discontinued in [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). The default scaffold now leverages the [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization) feature provided by [Controller-Runtime](https://github.com/kubernetes-sigs/controller-runtime).

This feature provides integrated support for securing metrics endpoints by embedding authentication (`authn`) and authorization (`authz`) mechanisms directly into the controller manager's metrics server, replacing the need for (https://github.com/brancz/kube-rbac-proxy) to secure metrics endpoints.

### What To Do?

**You must replace the deprecated image `gcr.io/kubebuilder/kube-rbac-proxy` with an alternative approach. For example:**
- Update your project to use [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization):
  > _You can fully upgrade your project to use the latest scaffolds provided by the tool or manually make the necessary changes. Refer to the [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907) for detailed instructions on how to manually update your project and test the changes._
- Alternatively, replace the image with another trusted source at your own risk, as its usage has been discontinued in Kubebuilder.

**For further information, suggestions, and guidance:**
- 📖 [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907)
- 💬 Join the Slack channel: [#kubebuilder](https://communityinviter.com/apps/kubernetes/community#kubebuilder).

> **NOTE:** _This issue was opened automatically as part of our efforts to identify projects that might be affected and to raise awareness about this change within the community. If your project is no longer using this image, **feel free to close this issue**._

We sincerely apologize for any inconvenience this may cause.

**Thank you for your cooperation and understanding!** :pray:

**Comment by ramperher** [comment]
Hi @camilamacedo86 , thanks for opening this issue. In our case, the usage of kube-rbac-proxy image comes from operator-sdk project. I've seen that, in latest release, [v1.38.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.38.0), it looks like it's discontinued the usage of kube-rbac-proxy in the default scaffolding of new projects. So we'll update to that release to avoid issues with this image (but anyway, we don't use it at all in the project, so we'll not be affected eventually). Thanks!

**Comment by camilamacedo86** [comment]
Hi @ramperher 

It was removed from Kubebuilder in the beginner of this year.
But SDK took a while to get the latest updates. 

I can see the usage of it in : https://github.com/search?q=repo%3Aopenshift-kni%2Fexample-cnf%20gcr.io%2Fkubebuilder%2Fkube-rbac-proxy&type=code

I did not check in all case scenarios, but it seems that you are not enabling the metrics: https://github.com/openshift-kni/example-cnf/blob/main/cnf-app-mac-operator/config/default/kustomization.yaml#L33

I recommend enabling the metrics since they can benefit users, but I also want to ensure their protection.

Suppose you can just re-scaffold the projects with the latest version of the tools and add your code on top. In that case, you will start to use [WithAuthenticationAndAuthorization](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization). This feature provides integrated support for securing metrics endpoints by embedding authentication (`authn`) and authorization (`authz`) mechanisms directly into the controller manager's metrics server, replacing the need for (https://github.com/brancz/kube-rbac-proxy) to secure metrics endpoints.

For production, it will also recommend ensuring certs,  see the feature that will be available in the next Kubebuilder release https://github.com/kubernetes-sigs/kubebuilder/pull/4400 to help out on it.

Also, for further information about metrics and how to protect it see ensure that you check: https://github.com/kubernetes-sigs/kubebuilder/discussions/3907

I hope that helps out.

**Comment by ramperher** [comment]
This is addressed here: https://github.com/openshift-kni/example-cnf/pull/108
Metrics are now enabled and in cnf-app-mac-operator, it has been included the usage of WithAuthenticationAndAuthorization.
Closing this, we'll follow up the work in that PR.
